ESSArch_Core/auth/__init__.py
This ensures that a 401 is returned when an unauthenticated request is made using sessions
=> Add custom SessionAuthentication class which returns 401

ESSArch_Core/frontend/scripts/configs/httpInterceptor.js
Add provider for angular http-requests handling response error codes and csrf tokens
=> Add provider for angular http-requests

ESSArch_Core/ip/views.py
Adds a basic InformationPackageViewSet which can be used and extended
=> Add InformationPackageViewSet

ESSArch_Core/frontend/styles/core/modules/buttons.scss, ESSArch_Core/frontend/styles/core/modules/colors.scss, ESSArch_Core/frontend/styles/core/modules/filebrowser.scss, ESSArch_Core/frontend/styles/core/modules/header.scss, ESSArch_Core/frontend/styles/core/modules/tables.scss, ESSArch_Core/frontend/views/formly_templates/datepicker_template.html, ESSArch_Core/frontend/views/login.html, ESSArch_Core/frontend/views/modals/change_node_organization.html, ESSArch_Core/frontend/views/modals/change_organization_modal.html, ESSArch_Core/frontend/views/modals/export_result_modal.html, ESSArch_Core/frontend/views/modals/step_info_modal.html, ESSArch_Core/frontend/views/modals/task_info_modal.html, ESSArch_Core/frontend/views/state_tree_view.html
Add font-awesome 5 compability and styling associated with design choices from font-awsome update.
=> Add font-awesome 5 compatibility

ESSArch_Core/frontend/scripts/controllers/StateTreeCtrl.js
Fixes bug where some steps/tasks would stay when changing IP
=> Empty tree data when IP is changed

ESSArch_Core/frontend/styles/core/modules/modals.scss
=> Add modal styles

ESSArch_Core/configuration/views.py
This also fixes a bug in Python 3 that occurred with the old code
=> Use PIP package to get installed packages

ESSArch_Core/frontend/views/modals/change_node_organization.html, ESSArch_Core/frontend/views/modals/change_organization_modal.html, ESSArch_Core/frontend/views/modals/export_result_modal.html, ESSArch_Core/frontend/views/modals/step_info_modal.html, ESSArch_Core/frontend/views/modals/task_info_modal.html
Use generic modal heading class and format modal template files
=> Use generic modal heading class

ESSArch_Core/frontend/styles/core/modules/utils.scss
=> Add flex row class

ESSArch_Core/.gitignore, ESSArch_Core/manage.py, ESSArch_Core/testapp/settings.py, ESSArch_Core/testapp/urls.py
This enables us to run the backend tests in this repository without using another application
=> Add testing application

setup.py
Add packages for optional support for SQL Server, PostgreSQL, and file conversion using Microsoft Office applications (Windows only)
=> Add more optional packages to setup.py

ESSArch_Core/frontend/scripts/components/UserDropdownComponent.js, ESSArch_Core/frontend/scripts/controllers/ChangePasswordModalCtrl.js, ESSArch_Core/frontend/scripts/controllers/UserDropdownCtrl.js, ESSArch_Core/frontend/styles/core/modules/login.scss, ESSArch_Core/frontend/views/modals/change_password_modal.html, ESSArch_Core/frontend/views/user_dropdown.html
=> Add User dropdown component and change password modal

ESSArch_Core/configuration/views.py
This is a way more portable and cross platform alternative to get the hostname of the system
=> Use Python std lib to get system hostname

setup.py
Fixes [CVE-2018-18074](https://nvd.nist.gov/vuln/detail/CVE-2018-18074)
=> Upgrade requests to 2.20.0

ESSArch_Core/frontend/scripts/configs/httpInterceptor.js, ESSArch_Core/frontend/scripts/controllers/NodeOrganizationModalInstanceCtrl.js, ESSArch_Core/frontend/scripts/controllers/NotificationsCtrl.js, ESSArch_Core/frontend/scripts/controllers/OrganizationModalInstanceCtrl.js, ESSArch_Core/frontend/scripts/controllers/StateTreeCtrl.js, ESSArch_Core/frontend/scripts/services/ErrorResponse.js, ESSArch_Core/frontend/tests/StateTreeCtrl.spec.js
Add translate to general error notifications and add better error handling on requests
=> Add better error handling

ESSArch_Core/frontend/scripts/controllers/NotificationsCtrl.js
=> Fix bug when options are undefined

ESSArch_Core/frontend/scripts/components/ImportComponent.js, ESSArch_Core/frontend/scripts/controllers/ImportCtrl.js, ESSArch_Core/frontend/views/import.html, ESSArch_Core/frontend/views/modals/profile-exists-modal.html, ESSArch_Core/frontend/views/modals/sa-exists-modal.html
Add import component and overwrite modal templates.
Add profile type input to component to allow current behaviour in ETP and ETA where we don't need all profiles from SA.
=> Add import component

ESSArch_Core/frontend/scripts/controllers/LoginCtrl.js, ESSArch_Core/frontend/views/login.html
=> Add loading indicator to login button

ESSArch_Core/frontend/styles/core/modules/step_task.scss, ESSArch_Core/frontend/views/state_tree_view.html, ESSArch_Core/frontend/views/treeGrid.html
* Position refresh button better
* Add heading
* fix text overflow by using paddings instead of "left" positioning
=> Update structure and styling of state tree 

ESSArch_Core/frontend/scripts/controllers/ImportCtrl.js
=> Fix bug with references to non imported profiles

ESSArch_Core/frontend/views/modals/step_info_modal.html, ESSArch_Core/frontend/views/modals/task_info_modal.html
* Update translations
* Only use label as modal title
* Hide elements when properties are empty
=> Update Step and task modals

ESSArch_Core/WorkflowEngine/filters.py, ESSArch_Core/WorkflowEngine/views.py, ESSArch_Core/auth/views.py, ESSArch_Core/filters.py, ESSArch_Core/fixity/views.py, ESSArch_Core/ip/filters.py, ESSArch_Core/ip/views.py, ESSArch_Core/maintenance/filters.py, ESSArch_Core/maintenance/views.py, ESSArch_Core/metadata.py, ESSArch_Core/profiles/views.py, setup.py
See the [Migration Guide](https://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-2-0) and the [Release Notes](https://github.com/carltongibson/django-filter/blob/2.0.0/CHANGES.rst) for changes in 2.0
=> Upgrade Django Filter to 2.0

ESSArch_Core/frontend/views/modals/task_traceback_modal.html
=> Use only task name as header text in traceback modal

ESSArch_Core/frontend/scripts/controllers/StateTreeCtrl.js, ESSArch_Core/frontend/scripts/controllers/StepInfoModalInstanceCtrl.js, ESSArch_Core/frontend/scripts/controllers/TaskInfoModalInstanceCtrl.js, ESSArch_Core/frontend/styles/core/modules/notifications.scss, ESSArch_Core/frontend/styles/core/modules/step_task.scss, ESSArch_Core/frontend/views/modals/step_info_modal.html, ESSArch_Core/frontend/views/modals/task_info_modal.html, ESSArch_Core/frontend/views/step_task_progressbar.html
Add more colors to progressbars
* Remove step_State column
* Add progressbar and improve design in step/task info modals
* Add more colors and popovers with step state to progressbars
* Update notification colors according to progressbar colors
=> Redesign step state indicators

ESSArch_Core/frontend/scripts/components/EventTableComponent.js, ESSArch_Core/frontend/scripts/controllers/EventCtrl.js, ESSArch_Core/frontend/styles/core/modules/events.scss, ESSArch_Core/frontend/views/event_table.html
=> Add event table with added styling similar to validations table

ESSArch_Core/frontend/styles/core/modules/import.scss, ESSArch_Core/frontend/styles/core/modules/utils/display.scss, ESSArch_Core/frontend/views/import.html
Add title, change button text on small screen and add styling for import page
=> Update import page layout

ESSArch_Core/frontend/views/modals/sa-exists-modal.html
=> Adjust button color

ESSArch_Core/frontend/views/event_table.html, ESSArch_Core/frontend/views/formly_templates/datepicker_template.html, ESSArch_Core/frontend/views/modals/step_info_modal.html, ESSArch_Core/frontend/views/modals/task_info_modal.html, ESSArch_Core/frontend/views/state_tree_view.html, ESSArch_Core/frontend/views/step_task_progressbar.html, ESSArch_Core/frontend/views/user_dropdown.html
* Change from popovers to tooltips where suited
* Use auto placement so that tooltips and popovers does not go outside
the screen. The have a default position but it will be re-evaluated if original placement is outside the screen.
=> Change popovers to tooltips

ESSArch_Core/frontend/views/sys_info_component.html
Do not line break component name
=> Add whitespace no-wrap to component name

ESSArch_Core/frontend/lang/en/userSettings.js, ESSArch_Core/frontend/lang/sv/userSettings.js, ESSArch_Core/frontend/scripts/controllers/UserDropdownCtrl.js
USERSETTINGS key needs to be available for browser tab translation
=> Fix browser tab title translation for user settings page

ESSArch_Core/test_util.py, ESSArch_Core/util.py
The tests are now covering more parts of the following functions:
- util.get_value_from_path
- util.get_files_and_dirs
- util.parse_content_range_header
- util.flatten
- util.getSchemas
=> Added tests to cover more of the util functions

ESSArch_Core/ip/tests/test_models.py
The tests are now covering more parts of the following functions:
- InformationPackage.status
=> Add tests to cover more of the InformationPackage model

ESSArch_Core/ip/tests/test_models.py
=> Add more test for InformationPackage.list_files

setup.py
Fixes [CVE-2019-6975](https://nvd.nist.gov/vuln/detail/CVE-2019-6975)
=> Upgrade Django to 1.11.20

ESSArch_Core/frontend/scripts/controllers/StateTreeCtrl.js, ESSArch_Core/frontend/scripts/services/StateTree.js, ESSArch_Core/frontend/tests/StateTreeCtrl.spec.js
Move functions from listViewService to new StateTree service in core
=> Add state tree service

ESSArch_Core/WorkflowEngine/models.py, ESSArch_Core/WorkflowEngine/serializers.py, ESSArch_Core/auth/admin.py, ESSArch_Core/auth/models.py, ESSArch_Core/auth/serializers.py, ESSArch_Core/filters.py, ESSArch_Core/fixity/validation/backends/checksum.py, ESSArch_Core/fixity/validation/backends/format.py, ESSArch_Core/fixity/validation/backends/xml.py, ESSArch_Core/forms/fields.py, ESSArch_Core/ip/models.py, ESSArch_Core/ip/permissions.py, ESSArch_Core/ip/serializers.py, ESSArch_Core/ip/views.py, ESSArch_Core/maintenance/serializers.py, ESSArch_Core/maintenance/views.py, ESSArch_Core/metadata.py, ESSArch_Core/pagination.py, ESSArch_Core/profiles/admin.py, ESSArch_Core/profiles/serializers.py, ESSArch_Core/profiles/views.py, ESSArch_Core/serializers.py
`super` in Python 3 requires no arguments, see [release notes](https://docs.python.org/3.0/whatsnew/3.0.html#builtins) and [PEP 3135](https://www.python.org/dev/peps/pep-3135/)
=> Replace super(ClassName, self) with super()

ESSArch_Core/ip/tasks.py, ESSArch_Core/ip/tests/test_utils.py, ESSArch_Core/ip/utils.py
Also added some tests to cover some parts of the functionalities.
This is to make it easier to unit test functionalities without involving
the complexity of celery.
=> Refactor/move functions from ip/tasks.py into ip/utils.py

ESSArch_Core/tasks.py, ESSArch_Core/tasks_util.py, ESSArch_Core/tests/test_tasks_util.py
Also added some tests to cover some parts of the functionalities.
This is to make it easier to unit test core functionalities without
involving the complexity of celery.
=> Refactor/move functions from tasks.py into tasks_util.py

ESSArch_Core/tasks.py, ESSArch_Core/tasks_util.py
IdentifyFileFormat was removed in 964cff03ba921f842f66c6eab796f21b299623a7
=> Fix usage of removed task

ESSArch_Core/maintenance/models.py, ESSArch_Core/maintenance/tests/test_views.py, ESSArch_Core/maintenance/views.py, ESSArch_Core/testapp/urls.py
Add tests for:
- AppraisalJobViewSet
- ConversionJobViewSet
=> Add test to cover more parts of maintenance.views

ESSArch_Core/maintenance/models.py, ESSArch_Core/maintenance/tests/test_models.py, ESSArch_Core/maintenance/tests/test_views.py
- Also moved tests for find_all_files from views to models.
- Minor cleanup of unused variables.
=> Add test to cover more parts of Maintenance.models

ESSArch_Core/fixity/validation/__init__.py
Fixes changes made in https://github.com/ESSolutions/ESSArch_Core/commit/ad761270312b43639588f3d0f617217fa65ea865
=> Fix validate_path not running validators

ESSArch_Core/auth/admin.py, ESSArch_Core/auth/signals.py, ESSArch_Core/maintenance/models.py, ESSArch_Core/tags/signals.py
=> Add logging when changes are made to users, groups, group types, roles and permissions

ESSArch_Core/maintenance/models.py
=> Fix job preview for conversion rules

.travis.yml, ESSArch_Core/storage/models.py, ESSArch_Core/storage/tests/test_models.py
Add tests for:
- get_storage_type_from_medium_type
- get_or_create_storage_medium
- StorageTarget._create_storage_medium
- StorageTarget.get_storage_backend
- StorageTarget.__str__
- StorageObject.get_root
- StorageObject.open
- StorageObject.read
- StorageObject.delete_files
=> Add test to cover storage.models

ESSArch_Core/frontend/scripts/components/FormErrorComponent.js, ESSArch_Core/frontend/scripts/configs/httpInterceptor.js, ESSArch_Core/frontend/scripts/controllers/FormErrorsCtrl.js, ESSArch_Core/frontend/styles/core/modules/form_errors.scss, ESSArch_Core/frontend/views/form_errors.html
* Add form error component for showing non field errors 
* Add option to skip next request error notification
=> Add form errors component and option to skip next error notification

.dockerignore, docker/Dockerfile, docker/docker-entrypoint.sh
Also speed up docker creation by ignoring some unnecessary folders/files
=> Create data folders on start of docker container.

.travis.yml, ESSArch_Core/cli/commands/settings.py, ESSArch_Core/config/__init__.py, ESSArch_Core/config/local_settings.default
This further indicates to the user how they can enable and disable the debug mode
=> Add debug flag to "generate settings"-command

ESSArch_Core/frontend/static/frontend/scripts/components/AdvancedFilterComponent.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/AdvancedFilterCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/BaseCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/CreateDipCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/EventCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/ReceptionCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/StorageMigrationCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/WorkareaCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/modules/essarch.components.module.js, ESSArch_Core/frontend/static/frontend/scripts/services/filters.ts, ESSArch_Core/frontend/static/frontend/styles/modules/tables.scss, ESSArch_Core/frontend/static/frontend/views/advanced_filters.html, ESSArch_Core/frontend/static/frontend/views/event_table.html, ESSArch_Core/frontend/static/frontend/views/list_view_table.html
* Extract functionality for advanced filters to one component that can be used for IP, event and storage medium tables.
* Add support for advanced filters for storage mediums
=> Add advanced filter component for IP, Event and storage medium tables.

ESSArch_Core/essxml/util.py, ESSArch_Core/fixity/validation/tests/tests.py
This fixes validation for the following type of nested structure with referenced external XML files
```
root
├── external
│   └── level2
│       ├── external
│       │   └── level3
│       │       ├── 1.txt
│       │       ├── 2.pdf
│       │       ├── 3.docx
│       │       └── level3.xml
│       └── level2.xml
└── root.xml
```
=> Fix diff-check for nested external XML files

ESSArch_Core/frontend/static/frontend/scripts/controllers/DeliveryCtrl.js
Fix javascript error when updating events for delivery
=> Fix bug when updating delivery event list

ESSArch_Core/essxml/tests/test_util.py, ESSArch_Core/essxml/util.py
While I was here, I also made the tests more explicit
=> Use case insensitive comparison to get fake premis file entry

.travis.yml, requirements/base.txt
[jsonfield2](https://pypi.org/project/jsonfield2/) is a fork of [jsonfield](https://pypi.org/project/jsonfield/) with support added for newer Django versions
=> Replace jsonfield with jsonfield2

requirements/base.txt
=> Bump django-nested-inline to 0.4.0

yarn.lock
Fixes https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
=> Bump webpack to 4.41.2

ESSArch_Core/workflow/tasks.py
=> Remove duplicate deletion

webpack.prod.babel.js
https://github.com/terser/terser#compress-options
=> Drop console calls in production build

ESSArch_Core/profiles/utils.py
Databases that have case sensitive collations doesn't work with iexact and will therefore not always return the expected value
=> Revert optimization of parameters and paths in fill_specification_data

ESSArch_Core/tags/models.py
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.0.0.html#breaking-7.0.0
=> Fix usage of field deprecated in Elasticsearch 7.0

ESSArch_Core/cli/main.py, docker/docker-compose.yml
Changes `-q` to `-Q` and adds `-n/--hostname` and `--pidfile`
=> Add more worker options from celery, match casing of queue option

ESSArch_Core/storage/models.py, ESSArch_Core/storage/tasks.py, ESSArch_Core/storage/tests/test_views.py
This fixes (and adds tests for) migration from a container based storage object to a non-container based storage object, and vice versa.
=> Fix storage migration between container and non-container

ESSArch_Core/cli/main.py, ESSArch_Core/cli/tests/test_main.py, requirements/base.txt
Reverts ESSolutions/ESSArch#1071
=> Revert "Set default celery execution pool to gevent"

ESSArch_Core/fixity/models.py, ESSArch_Core/fixity/validation/__init__.py, ESSArch_Core/ip/tasks.py
=> Generic validation task

ESSArch_Core/frontend/static/frontend/scripts/controllers/ConversionCtrl.js, ESSArch_Core/frontend/static/frontend/views/action_details_modal.html, ESSArch_Core/frontend/static/frontend/views/conversion_view.html
*Before submitting this pull request, please review our [contributing guidelines](https://github.com/ESSolutions/ESSArch_Core/blob/master/.github/CONTRIBUTING.md)*
Please describe your pull request.
*Patches should be made against master.*
*If it fixes a bug or resolves a feature request,
be sure to link to that issue, eg. "fixes #6789".*
=> Run action tool bug fix

ESSArch_Core/frontend/static/frontend/scripts/controllers/ConversionCtrl.js
*Before submitting this pull request, please review our [contributing guidelines](https://github.com/ESSolutions/ESSArch_Core/blob/master/.github/CONTRIBUTING.md)*
Please describe your pull request.
*Patches should be made against master.*
*If it fixes a bug or resolves a feature request,
be sure to link to that issue, eg. "fixes #6789".*
=> Conversion View- controller update for dropdown
