ESSolutions/ESSArch

ESSArch_Core/WorkflowEngine/serializers.py
Previously params could include complex objects which were complicated
to serialize. Now we always use simple objects which doesn't require any
special treatment. We instead let DRF and/or Django handle the
serialization.
=> Fix serialization of task params in Python 3

ESSArch_Core/auth/models.py, ESSArch_Core/auth/signals.py
Renaming the signal doesn't affect anything but is a better description of what it does.
If a group doesn't have a type we get an AttributeError when checking the codename. This is fixed by first checking if the `group_type` attribute is `None`.
=> Minor auth fixes

ESSArch_Core/auth/tests/test_backends.py, ESSArch_Core/auth/tests/test_signals.py, ESSArch_Core/auth/tests/test_util.py, ESSArch_Core/auth/util.py
Tests are split up into different file matching the files they are testing. This PR also includes a minor fix for getting objects when user is not part of an organization but has an object assigned directly to them or to one of their groups.
=> Add and restructure authentication tests

ESSArch_Core/essxml/tests/test_util.py
The file is opened in binary mode and thus requires binary data when written to
=> Fix ParseSubmitDescriptionTestCase in Python 3

ESSArch_Core/ip/views.py
The `change_profile` method in the InformationPackage model was deleted in https://github.com/ESSolutions/ESSArch_Core/commit/35abc3f0d4ccff4d9d311a3f8b3b976ed0914c22
=> Remove unused IP view method

ESSArch_Core/fixity/validation/backends/structure.py, ESSArch_Core/search/importers/earderms.py
* `message` attribute no longer exists in `Exception` objects. Use `logger.exception` to log the exception instead
* `itertools.izip` has been replaced with `zip`, use six to be compatible with both
=> Minor Python 3 fixes

ESSArch_Core/essxml/Generator/tests/test_generate.py
Fido prints an error when processing empty files which makes the test output a bit noisy. This PR fixes that by adding some content to the test files.
=> Use non-empty files in tests to avoid errors from fido

ESSArch_Core/WorkflowEngine/models.py
Since Celery 4, groups does not accept the link_error argument. And since chords can't have an error callback without a "regular" callback we temporarily instead assign the same link_error to all tasks in the group/chain.
=> Celery 4 group link error

ESSArch_Core/maintenance/serializers.py, ESSArch_Core/maintenance/tests/test_views.py, ESSArch_Core/testapp/urls.py
This is a fix for DRF 3.8 which changed how default values are handled for read_only fields. We also ensure that `public` gets a proper default value.
=> Fix appraisal rule-creation API

ESSArch_Core/tasks.py
Before looking into how to optimize the loop we lower the amount of iterations
=> Lower amount of tags popped from tag queues each time task is executed

ESSArch_Core/fixity/validation/tests.py
Files created using `tempfile.NamedTemporaryFile` cannot be opened twice in Windows without closing the first one. We solve this by disabling the automatic deletion and instead manually close and delete the files
=> Fix ChecksumValidatorXMLTests on Windows

setup.py
regex is a dependency of awesome-slugify (dependency of django-groups-manager) which does not have a version of regex specified. This can (and has) lead to an unstable regex version being installed.
Locking it to a specific version gives us more control and stability in how it is used.
=> Lock regex package to 2018.08.29

ESSArch_Core/essxml/Generator/tests/test_generate.py, ESSArch_Core/essxml/Generator/xmlGenerator.py
This allows us to create elements like this:
``` xml
<foo bar=""/>
```
=> XML Generator: Add support for creating empty attributes

ESSArch_Core/filters.py
`DateRangeWidget` uses the more appropriate _after_ and _before_ suffixes instead of the default of _min_ and _max_ from `RangeWidget`
=> Use DateRangeWidget for IsoDateTimeRangeField

ESSArch_Core/search/importers/earderms.py, ESSArch_Core/tags/signals.py, ESSArch_Core/tasks.py
By using django-redis to get the client we ensure that the correct configuration will be used.
=> Use django-redis to get raw client

ESSArch_Core/storage/migrations/0006_auto_20170406_2007.py, ESSArch_Core/storage/models.py
Fixes the problem with users having to add a IOQueue-entry when creating tape drives using the django admin interface
=> Allow TapeDrive.io_queue_entry to be blank

ESSArch_Core/WorkflowEngine/models.py, ESSArch_Core/configuration/models.py, ESSArch_Core/ip/models.py, ESSArch_Core/profiles/models.py
In Python 3 the `__unicode__` method was replaced by the `__str__` method
=> Rename __unicode__ methods to __str__

ESSArch_Core/tasks.py
If we are on Windows and the errno is 267, then we don't want to try to delete the file again.
=> Fix error handling in DeleteFiles on Windows

ESSArch_Core/tags/models.py
The `data`-field is replaced by `attachment.content` using the pipeline during indexing, therefore only  `attachment.content` has to be excluded
=> Exclude attachment.content when getting tag doc

ESSArch_Core/configuration/views.py, ESSArch_Core/frontend/scripts/components/SysInfoComponent.js, ESSArch_Core/frontend/scripts/controllers/SysInfoComponentCtrl.js, ESSArch_Core/frontend/scripts/controllers/VersionCtrl.js, ESSArch_Core/frontend/styles/core/modules/sysinfo.scss, ESSArch_Core/frontend/styles/core/modules/utils/flex.scss, ESSArch_Core/frontend/styles/core/modules/utils/spacing.scss, ESSArch_Core/frontend/views/sys_info_component.html, ESSArch_Core/frontend/views/sysinfo.html
* Get more specific platform information
* Add icons for Python, OS, database and time information
* List python packages in a table
* Make the page more responsive
* Add ESSArch Core version info
=> Redesign sysinfo page

ESSArch_Core/configuration/views.py, ESSArch_Core/frontend/scripts/controllers/VersionCtrl.js
[`platform.linux_distribution`](https://docs.python.org/3.6/library/platform.html#platform.linux_distribution) is deprecated in Python 3.5 and will be removed in 3.8. If we want to keep getting the same data after that we can use the [distro](https://pypi.org/project/distro) package recommended by Python
=> Use better data for linux dist and version

ESSArch_Core/essxml/Generator/tests/test_generate.py, ESSArch_Core/essxml/Generator/xmlGenerator.py, ESSArch_Core/fixity/validation/__init__.py, ESSArch_Core/fixity/validation/backends/structure.py, ESSArch_Core/fixity/validation/backends/xml.py, ESSArch_Core/ip/admin.py, ESSArch_Core/ip/tasks.py, ESSArch_Core/maintenance/models.py, ESSArch_Core/maintenance/views.py, ESSArch_Core/storage/backends/s3.py, ESSArch_Core/storage/copy.py, ESSArch_Core/tasks.py, ESSArch_Core/util.py, setup.py
`scandir` is built-in to Python since 3.5: https://docs.python.org/3/whatsnew/3.5.html#pep-471-os-scandir-function-a-better-and-faster-directory-iterator
=> Use built-in scandir

ESSArch_Core/WorkflowEngine/tests/test_tasks.py, ESSArch_Core/essxml/Generator/tests/test_generate.py, ESSArch_Core/essxml/tests/test_util.py, ESSArch_Core/fixity/receipt/tests.py, ESSArch_Core/fixity/test_format.py, ESSArch_Core/ip/tests/test_models.py, ESSArch_Core/storage/tests.py, ESSArch_Core/test_util.py, setup.py
`mock` is built-in to Python since 3.3: https://docs.python.org/3/whatsnew/3.3.html
=> Use built-in mock

ESSArch_Core/WorkflowEngine/dbtask.py, ESSArch_Core/WorkflowEngine/tests/test_tasks.py
When a user is set as responsible for a task we use [`translation.override`](https://docs.djangoproject.com/en/1.11/ref/utils/#django.utils.translation.override) to temporarily set the language used in the task to generate the correct language for different messages and values, e.g. notifications sent to the user when a task completes.
=> Use language of responsible user when running tasks

setup.py
Adds Python 3.7 support (1.11.17) and fixes CVE-2019-3498 (1.11.18)
=> Upgrade Django to 1.11.18

setup.py
Prepares us for Django 2 and enables more i18n customisation
=> Upgrade django-groups-manager to 0.6.2

ESSArch_Core/search/alias_migration.py
Line 62 is the changed one, but the whole file also went from CRLF to LF
=> Fix elasticsearch alias migration in Python 3

ESSArch_Core/fixity/format.py, setup.py
By specifying the format files to fido we can use version 1.3.12 even though it is broken.
The upgrade to 1.3.12, among other things, adds the following features  
* allows us to bump up six which avoids some version conflicts
* greatly increases the performance for determining formats of some TIFF-files
=> Upgrade opf-fido to 1.3.12

ESSArch_Core/WorkflowEngine/dbtask.py, ESSArch_Core/WorkflowEngine/models.py, ESSArch_Core/WorkflowEngine/tests/tasks.py, ESSArch_Core/auth/models.py, ESSArch_Core/configuration/models.py, ESSArch_Core/essxml/util.py, ESSArch_Core/fixity/checksum.py, ESSArch_Core/fixity/format.py, ESSArch_Core/fixity/validation/backends/checksum.py, ESSArch_Core/fixity/validation/backends/format.py, ESSArch_Core/fixity/validation/backends/mediaconch.py, ESSArch_Core/fixity/validation/backends/structure.py, ESSArch_Core/fixity/validation/backends/verapdf.py, ESSArch_Core/fixity/validation/tests.py, ESSArch_Core/ip/models.py, ESSArch_Core/profiles/models.py, ESSArch_Core/storage/models.py, ESSArch_Core/util.py
We have upgraded to Python 3, we no longer require tools that makes the migration easier
=> Remove Python 2/3 compatibility imports

ESSArch_Core/util.py
Python 3.2  added the `exist_ok` parameter to `os.makedirs`, making `mkdir_p` unnecessary
=> Remove mkdir_p

ESSArch_Core/maintenance/models.py
AppraisalJob had a `Meta` class that didn't inherit from `MaintenanceJob.Meta` which meant that `get_latest_by` wasn't set. This led to `.earliest` and `.latest` not working for appraisal jobs
=> Fix bug when getting earliest/latest appraisal job

ESSArch_Core/test_util.py, ESSArch_Core/util.py
As a side effect, we can mock the get_filename_from_file_obj for easier testing.
=> Extract/Move out getting filename from generate_file_response

ESSArch_Core/WorkflowEngine/migrations/0001_initial.py, ESSArch_Core/WorkflowEngine/models.py
This stops Django from wanting to create new migrations with different order of the choices
=> Sort ProcessTask status choices

ESSArch_Core/WorkflowEngine/views.py, ESSArch_Core/auth/views.py, ESSArch_Core/ip/views.py, ESSArch_Core/maintenance/views.py, ESSArch_Core/profiles/views.py
`detail_route` and `list_route` were deprecated and replaced by the `action` decorator in Django Rest Framework 3.8. Release notes: https://www.django-rest-framework.org/community/3.8-announcement/#action-decorator-replaces-list_route-and-detail_route
=> Replace detail/list_routes with action decorator

codecov.yml
This reverts commit 8b99265e93a47c5616c9b094a70155983766ca78 which didn't seem to have any effect
=> Revert "Disabel patch status on codecov (#226)"

ESSArch_Core/ip/tests/test_models.py
New tests are covering more parts of:
- get_agent
- is_first_generation()
- is_last_generation()
- get_lock_key()
- is_locked()
- get_checksum_algorithm()
- get_email_recipient()
- get_container_format()
- get_path()
=> Add tests to cover more of InformationPackage

ESSArch_Core/filters.py, ESSArch_Core/forms/fields.py, ESSArch_Core/ip/filters.py, ESSArch_Core/tests/test_filters.py, setup.py
[2.1.0](https://github.com/carltongibson/django-filter/releases/tag/2.1.0) now includes `IsoDateTimeFromToRangeFilter` which means that we can delete our copy
=> Upgrade Django Filter to 2.1.0

ESSArch_Core/frontend/scripts/services/EditMode.js
Add service that adds a confirmation if user is trying to close browser window or refresh browser.
Can be enabled or disabled for example when opening certain modals or edit other things
=> Add EditMode service

ESSArch_Core/WorkflowEngine/tests/test_steps.py
Direct assignment to a reverse foreign key or many-to-many relation was [deprecated](https://docs.djangoproject.com/en/2.1/releases/1.10/#direct-assignment-to-a-reverse-foreign-key-or-many-to-many-relation) in Django 1.10
=> Fix deprecated reverse relation assignment

ESSArch_Core/WorkflowEngine/__init__.py, ESSArch_Core/configuration/views.py, ESSArch_Core/frontend/views/sysinfo.html
- Add error handling for RabbitMQ
- Add error handling for Redis
- Add error handling for celery workers
- Also add support for fetching only version or full detailed info from RabbitMQ and Redis services.
=> /api/sysinfo should work even when services are down.

ESSArch_Core/tasks_util.py
When filterng EventIP objects with IP it expects the primary key of the IP, not an IP object.
=> Fix how events are fetched from IP

.travis.yml
The chocolatey package is missing and has not been fixed for more than a week, so lets do it the old-fashion way
=> Install msodbcsql 17 on travis-Windows without chocolatey

ESSArch_Core/auth/tests/test_backends.py, ESSArch_Core/auth/util.py
```
+-------+ Sweden +------+
|                       |
|                       |
v                       v
Stockholm                Uppsala
```
With the group hierarchy above and a user that has read permission in `Sweden` and write permission in `Stockholm`, this updates gives that user read permission in all three groups but only write permission in `Stockolm`.
=> Use ancestor roles when querying user objects

ESSArch_Core/fixity/receipt/__init__.py, ESSArch_Core/ip/tasks.py
Receipt backends does not accept any initialisation arguments since #100
=> Fix receipt backend retrieval from CreateReceipt task

ESSArch_Core/WorkflowEngine/tests/test_views.py, ESSArch_Core/WorkflowEngine/views.py, ESSArch_Core/testapp/urls.py
This ensures that `/api/steps/{step_id}/tasks/` only returns tasks that belongs to the step. Regression in #19
=> Fix and test list of tasks in step api

ESSArch_Core/cli/main.py
This adds a `devserver` command to the CLI which uses the built-in webserver provided by Django.
=> Add devserver command to CLI

ESSArch_Core/ip/migrations/0081_auto_20190930_1112.py, ESSArch_Core/ip/migrations/0082_auto_20190930_1553.py
Earlier if there was any data in the Order table there could be errors when the consign_method field was changed from a CharField to a ForeignKey (int).
Reported error in MariaDB:
```
django.db.utils.DataError: (1265, "Data truncated for column 'consign_method_id' at row 1")
```
=> Simplify migrations for ConsignMethod

ESSArch_Core/api/tests/test_filters.py, ESSArch_Core/auth/tests/test_decorators.py, ESSArch_Core/config/settings.py, ESSArch_Core/ip/views.py, ESSArch_Core/tags/views.py
By default we want all views to be protected by permissions to ensure that we don't miss any new views that we don't do any custom changes to.
=> Set default permission class for all views to ActionPermissions

ESSArch_Core/frontend/static/frontend/scripts/controllers/ArchiveModalInstanceCtrl.js
The javascript code is trying to set "disabled" property of uuid string and prevents edit form from rendering. 
Occurs when an archives structure is not published.
=> Fix bug with form rendering when trying to edit archive with unpublished structure

ESSArch_Core/frontend/static/frontend/scripts/controllers/BaseCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/EventCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/services/filters.ts
Building IP and event filters took too long due to timeouts.
* Remove $timeout and make the first call to the filter data creation function when selected IP etc is calculated
* Split filter form creation into 2 functions to avoid unneccesary work. The actual fields are now created the first time advanced filter is opened and the default values (form model) is created when page is initialized.
=> Fix filter performance issue

ESSArch_Core/storage/filters.py, ESSArch_Core/storage/models.py, ESSArch_Core/storage/tests/test_views.py
This filter lets users list storage mediums which has new storage mediums
available for migration to them. It will only list mediums that contain atleast one IP
not yet migrated to the new medium.
=> Add "migratable" filter for storage mediums

ESSArch_Core/essxml/Generator/xmlGenerator.py
Previously we would get a non-descriptive error when trying to create external XML-files in non-existing subdirectories of the specified external root directory.
Now we instead catch the error and log a more descriptive message.
=> Fix error when external dirs have no subdirectories

ESSArch_Core/essxml/Generator/tests/test_generate.py, ESSArch_Core/essxml/Generator/xmlGenerator.py
This fixes cases such as when you have a specified external directory named  `foo` and another non-external directory named `bar/foo`.
Previously files from `bar/foo` would be excluded because we only looked at the basename of each directory. With this change we compare the full relative path, i.e. `bar/foo`.
=> XML: Compare full relative path when skipping external dirs

ESSArch_Core/ip/models.py
This allows us to reuse values defined in the SA template in the profiles relations for the information package
=> Use SA default values when creating ip-profile relations

ESSArch_Core/storage/serializers.py
This provides us with some guarantees for future improvements such as sorting for best I/O performance and possibly migration to same target for redundant storage.
=> Require all IPs in migration request to have the same policy

ESSArch_Core/essxml/util.py, ESSArch_Core/fixity/validation/tests/test_xml_schema_validator.py, ESSArch_Core/ip/utils.py, ESSArch_Core/tests/test_util.py, ESSArch_Core/util.py
libxml2 which lxml uses, does currently not support schemas which imports external schemas using https.
To fix this we download the required schemas and update the import elements to instead point to the local copies. The modification is only done in memory so that the schema files are not changed and the local copies are deleted when the validation is finished.
=> Fix XML validation against schemas with https imports

ESSArch_Core/util.py
```
http://www.loc.gov/METS/ http://xml.essarch.org/METS/version11/ESSPackageMETS.xsd ExtensionMETS http://xml.ra.se/e-arkiv/METS/version11/CSPackageExtensionMETS.xsd
```
```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:import namespace="http://www.loc.gov/METS/" schemaLocation="http://xml.essarch.org/METS/version11/ESSPackageMETS.xsd"/>
<xsd:import namespace="http://xml.essarch.org/METS/version11/ESSPackageMETS.xsd" schemaLocation="ExtensionMETS"/>
<xsd:import namespace="ExtensionMETS" schemaLocation="http://xml.ra.se/e-arkiv/METS/version11/CSPackageExtensionMETS.xsd"/>
</xsd:schema>
```
```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:import namespace="http://www.loc.gov/METS/" …
```
=> Fix getSchemas when working with multiple schemas in schemaLocation

ESSArch_Core/essxml/util.py, ESSArch_Core/ip/models.py, ESSArch_Core/ip/tests/test_models.py, ESSArch_Core/util.py, ESSArch_Core/workflow/tasks.py
METS files in SIPs might have data that can't be found in the database and that we want to reuse for the AIP
=> Parse and store SIP mets data in AIP profile in ReceiveSIP

ESSArch_Core/config/settings.py
See [the docs](https://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html#default-connection) for examples
=> Fix default ELASTICSEARCH_CONNECTIONS

ESSArch_Core/frontend/static/frontend/scripts/configs/formlyConfig.js
Recommended by angular-formly and the official documentation:
* http://docs.angular-formly.com/docs/tips#section-api-check
* https://github.com/kentcdodds/api-check#disable-apicheck
=> Disable api-check globally

requirements/base.txt
[Release notes](https://docs.djangoproject.com/en/stable/releases/2.2.8/)
=> Bump django to 2.2.8

yarn.lock
Also bumps related types packages @types/angular and @types/angular-translate
Closes #745
Closes #747
Closes #749
Closes #751
Closes #754
Closes #755
Closes #758
Closes #768
=> Bump official AngularJS packages to 1.7.9

ESSArch_Core/fixity/receipt/backends/base.py, ESSArch_Core/fixity/receipt/backends/email.py, ESSArch_Core/fixity/receipt/backends/xml.py, ESSArch_Core/fixity/receipt/tests/tests.py, ESSArch_Core/ip/tasks.py, ESSArch_Core/profiles/utils.py
With the optional parameter `attachments` added to the email backend and the XML backend returning its destination, the following configuration will add the XML receipt as an attachment to the email receipt
```json
[
{
"name":"ESSArch_Core.ip.tasks.CreateReceipt",
"label":"Create XML receipt",
"reference": "xml_receipt",
"args": [
null,
"xml",
"receipts/xml.json",
"/ESSArch/data/receipts/{{_OBJID}}_{% now 'ymdHis' %}.xml",
"success",
"Preserved {{OBJID}}",
"{{OBJID}} is now preserved"
],
},
{
"name": "ESSArch_Core.ip.tasks.CreateReceipt",
"label": "Send email receipt",
"args": [
null,
"email",
"receipts/email.txt",
"mail@example.com",
"success",
"Preserved {{OBJID}}",
"{{OBJID}} is now preserved"
],
"result_params": {
"attachments": ["xml_receipt"]
}
}
]
```
=> Add ability to attach xml receipt to email receipt

ESSArch_Core/essxml/util.py, ESSArch_Core/tasks.py
By using a setter with `normalize_path` in  `XMLFileElement` for `path`, and `PurePath` instead of `PurePosixPath` in `CompareRepresentationXMLFiles` we can be more confident in that the paths are handled correctly no matter which platform, or types of paths we are working with.
=> Improve XML validation on Windows

ESSArch_Core/frontend/static/frontend/scripts/services/SelectedIPUpdater.js
For some reason this function checked for both equal ID and object_identifier_value, which does not make any sense since both ID and object_identifier_value are unique identifiers
=> Fix bug when updating medium list

ESSArch_Core/ip/tests/test_ips.py
Fido complains when working with empty files. So instead we now create a real tar file and add the source file to it. We also create a real temporary directory instead of creating test files inside the repo.
=> Remove fido warnings from tests

ESSArch_Core/frontend/static/frontend/scripts/controllers/AgentArchiveRelationModalInstanceCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/PlaceNodeInArchiveModalInstanceCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/controllers/StructureUnitRelationModalInstanceCtrl.js, ESSArch_Core/frontend/static/frontend/scripts/modules/essarch.controllers.module.js, ESSArch_Core/frontend/static/frontend/scripts/modules/essarch.services.module.js, ESSArch_Core/frontend/static/frontend/scripts/services/archiveName.js
* Solves bug where archive dropdown list appeared empty when the list contained archives with start/end-dates. Caused by missing $filter injection.
* Extract function for archive names with dates to own service so that it can be reused without getting the same error.
=> Fix bug where archive dropdown list appeared empty

ESSArch_Core/WorkflowEngine/dbtask.py, ESSArch_Core/WorkflowEngine/tests/test_steps.py, ESSArch_Core/WorkflowEngine/tests/test_tasks.py, ESSArch_Core/celery/backends/database.py, ESSArch_Core/ip/tests/test_ips.py, ESSArch_Core/testing/runner.py
This PR removes the customized version of DBTask.apply() and instead uses DBTask.success and DBTask.failure to update the database when eager tasks succeeds or fails.
By using the built-in DBTask.apply() we get proper task propagation that is better suited for testing
=> Add error propagation to eager tasks

ESSArch_Core/tags/serializers.py, ESSArch_Core/tags/tests/test_views.py
Fixes arguments sent to create_identifiers and create_notes as well as correctly setting default value for `information_package` when updating component
=> Cleanup, fix and test ArchiveWriteSerializer and ComponentWriteSerializer

.github/workflows/main.yml
[Release notes](https://github.com/codecov/codecov-action/releases/tag/v1.0.6)
=> Bump codecov action to 1.0.6

ESSArch_Core/frontend/static/frontend/views/home.html
From the [documentation](https://docs.angularjs.org/api/ng/directive/ngSrc):
> Using AngularJS markup like {{hash}} in a src attribute doesn't work right: The browser will fetch from the URL with the literal text {{hash}} until AngularJS replaces the expression inside {{hash}}. The ngSrc directive solves this problem.
=> Remove failing request for custom logo

ESSArch_Core/ip/models.py, ESSArch_Core/ip/views.py
Mets and premis files are created when preserving the package and are therefore not needed when moving packages from workarea to approval
=> Remove creation of mets and premis at workarea access

.dockerignore, ESSArch_Core/frontend/static/frontend/scripts/configs/preventTemplateCache.js, ESSArch_Core/frontend/static/frontend/scripts/modules/essarch.configs.module.js, docker/Dockerfile, package.json, webpack.common.babel.js, yarn.lock
This extends the requested url for each template with the commit hash used when the frontend was last built. This makes the browser invalidate the cached template whenever a new build is made.
=> Invalidate template cache when commit hash changes

package.json, yarn.lock
Remove security issue package
ng-annotate-webpack-plugin@0.3.0 requires minimist@~0.0.1 via a transitive dependency on optimist@0.6.1
Minimist prior to 1.2.6 and 0.2.4 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).
=> Remove dep ng-annotate-webpack-plugin

ESSArch_Core/ip/views.py
Sort the content of an archived IP alphabetically based on file/directory name. This matches the behavior when the IP is not archived and the files are just in a directory.
=> Sort content of archived IPs alphabetically

ESSArch_Core/frontend/static/frontend/lang/en/ip.ts, ESSArch_Core/frontend/static/frontend/lang/sv/ip.ts, ESSArch_Core/frontend/static/frontend/scripts/controllers/IpApprovalCtrl.js, ESSArch_Core/frontend/static/frontend/views/search_ip_detail.html, ESSArch_Core/tags/serializers.py, ESSArch_Core/tasks.py
This adds a new state 'Aggregating', used by the University of Gothenburg for AIPs that are being created from multiple SIPs over time. IPs in this state should be in the 'Checkpoint' view for now.
This also makes links to such packages in the archival description lead to the view where the package can be found.
=> Add 'Aggregating' state
